/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.utxicotepec.saborlocal.Vendedor;

import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import mx.edu.utxicotepec.saborlocal.Controllers.PedidoPersonalizadoController;
import mx.edu.utxicotepec.saborlocal.Model.PedidoPersonalizado2Model;
import mx.edu.utxicotepec.saborlocal.Model.PedidoPersonalizadoModel;

/**
 *
 * @author xidon
 */
public class FrmPastelPersonalizado extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPastelPersonalizado.class.getName());

    /**
     * Creates new form FrmPastelPersonalizado
     */
    public FrmPastelPersonalizado() {
        initComponents();
        cargarDatosComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboforma = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combosabor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        combotama = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combodecora = new javax.swing.JComboBox<>();
        combovubierta = new javax.swing.JComboBox<>();
        btnsiguiente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnatras1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        combocliente = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboocasion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 240, 217));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));

        jLabel1.setBackground(new java.awt.Color(255, 240, 217));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tipo de Pan");

        combotipo.setBackground(new java.awt.Color(255, 255, 255));
        combotipo.setEditable(true);
        combotipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combotipo.setForeground(new java.awt.Color(0, 0, 0));
        combotipo.setPreferredSize(new java.awt.Dimension(180, 50));

        jLabel2.setBackground(new java.awt.Color(255, 240, 217));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Forma");

        comboforma.setBackground(new java.awt.Color(255, 255, 255));
        comboforma.setEditable(true);
        comboforma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comboforma.setForeground(new java.awt.Color(0, 0, 0));
        comboforma.setPreferredSize(new java.awt.Dimension(180, 100));

        jLabel3.setBackground(new java.awt.Color(255, 240, 217));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Sabor");

        combosabor.setBackground(new java.awt.Color(255, 255, 255));
        combosabor.setEditable(true);
        combosabor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combosabor.setForeground(new java.awt.Color(0, 0, 0));
        combosabor.setPreferredSize(new java.awt.Dimension(180, 50));

        jLabel4.setBackground(new java.awt.Color(255, 240, 217));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tamaño");

        combotama.setBackground(new java.awt.Color(255, 255, 255));
        combotama.setEditable(true);
        combotama.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combotama.setForeground(new java.awt.Color(0, 0, 0));
        combotama.setPreferredSize(new java.awt.Dimension(180, 100));

        jLabel5.setBackground(new java.awt.Color(255, 240, 217));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cubierta");

        jLabel6.setBackground(new java.awt.Color(255, 240, 217));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Decoración");

        combodecora.setBackground(new java.awt.Color(255, 255, 255));
        combodecora.setEditable(true);
        combodecora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combodecora.setForeground(new java.awt.Color(0, 0, 0));
        combodecora.setPreferredSize(new java.awt.Dimension(180, 100));

        combovubierta.setBackground(new java.awt.Color(255, 255, 255));
        combovubierta.setEditable(true);
        combovubierta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combovubierta.setForeground(new java.awt.Color(0, 0, 0));
        combovubierta.setPreferredSize(new java.awt.Dimension(180, 100));

        btnsiguiente.setBackground(new java.awt.Color(255, 255, 255));
        btnsiguiente.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnsiguiente.setForeground(new java.awt.Color(0, 0, 0));
        btnsiguiente.setText("Siguiente");
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(185, 157, 179));
        jPanel2.setForeground(new java.awt.Color(185, 157, 179));
        jPanel2.setPreferredSize(new java.awt.Dimension(1440, 100));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Pastel Personalizado");

        btnatras1.setBackground(new java.awt.Color(185, 157, 179));
        btnatras1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnatras1.setForeground(new java.awt.Color(255, 240, 217));
        btnatras1.setIcon(new javax.swing.ImageIcon("C:\\Users\\xidon\\Documents\\NetBeansProjects\\SaborLocal\\resources\\imgs\\Arrow 2.png")); // NOI18N
        btnatras1.setPreferredSize(new java.awt.Dimension(100, 100));
        btnatras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnatras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(508, 508, 508))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnatras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(21, 21, 21))
        );

        jLabel8.setBackground(new java.awt.Color(255, 240, 217));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cliente");

        combocliente.setBackground(new java.awt.Color(255, 255, 255));
        combocliente.setEditable(true);
        combocliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combocliente.setForeground(new java.awt.Color(0, 0, 0));
        combocliente.setPreferredSize(new java.awt.Dimension(180, 100));

        jLabel9.setBackground(new java.awt.Color(255, 240, 217));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ocasion");

        comboocasion.setBackground(new java.awt.Color(255, 255, 255));
        comboocasion.setEditable(true);
        comboocasion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comboocasion.setForeground(new java.awt.Color(0, 0, 0));
        comboocasion.setPreferredSize(new java.awt.Dimension(180, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboocasion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combodecora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combosabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3)))))
                .addGap(217, 217, 217)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combovubierta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(combotipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combotama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(161, 161, 161))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(148, 148, 148))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combosabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboforma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(103, 103, 103))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(95, 95, 95)
                                            .addComponent(combovubierta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel2))
                                            .addGap(103, 103, 103)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(53, 53, 53)
                                        .addComponent(combocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combotama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combodecora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(comboocasion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(53, 53, 53)
                        .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(228, 228, 228)
                .addComponent(btnsiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
        siguiente();
    }//GEN-LAST:event_btnsiguienteActionPerformed

    private void btnatras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatras1ActionPerformed
        // TODO add your handling code here:
        FrmRegistroPedido frmmenu = new FrmRegistroPedido();
        frmmenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnatras1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPastelPersonalizado().setVisible(true));
    }

    private void cargarDatosComboBoxes() {
        // 1. Cargar Clientes
        List<String> clientes = PedidoPersonalizadoController.obtenerClientes();
        for (String cliente : clientes) {
            combocliente.addItem(cliente);
        }

        // 2. Cargar Tipos de Pan
        List<String> tiposPan = PedidoPersonalizadoController.obtenerValoresUnicos("tipo_pan");
        for (String tipo : tiposPan) {
            combotipo.addItem(tipo);
        }

        // 3. Cargar Sabores
        List<String> sabores = PedidoPersonalizadoController.obtenerValoresUnicos("sabor");
        for (String sabor : sabores) {
            combosabor.addItem(sabor);
        }

        // 4. Cargar Cubiertas
        List<String> cubiertas = PedidoPersonalizadoController.obtenerValoresUnicos("cubierta");
        for (String cubierta : cubiertas) {
            combovubierta.addItem(cubierta);
        }

        // 5. Cargar Formas
        List<String> formas = PedidoPersonalizadoController.obtenerValoresUnicos("forma");
        for (String forma : formas) {
            comboforma.addItem(forma);
        }

        // 6. Cargar Tamaños
        // ✅ Aquí está el error. Estás llamando al método incorrecto.
        // List<String> tamanos = PedidoPersonalizadoController.obtenerValoresUnicos("tamanio");
        // ✅ La solución es crear un método nuevo y llamarlo aquí.
        List<String> tamanos = PedidoPersonalizadoController.obtenerNombresTamanios();
        for (String tamano : tamanos) {
            combotama.addItem(tamano);
        }

        // 7. Cargar Decoraciones
        List<String> decoraciones = PedidoPersonalizadoController.obtenerValoresUnicos("decoracion");
        for (String decoracion : decoraciones) {
            combodecora.addItem(decoracion);
        }

        // 8. Cargar Ocasiones
        List<String> ocasiones = PedidoPersonalizadoController.obtenerValoresUnicos("ocasion");
        for (String ocasion : ocasiones) {
            comboocasion.addItem(ocasion);
        }
    }

    public void siguiente() {
        // 1. Recopila los datos de los JComboBox
        String cliente = (String) combocliente.getSelectedItem();
        String ocasion = (String) comboocasion.getSelectedItem();
        String tipoPan = (String) combotipo.getSelectedItem();
        String sabor = (String) combosabor.getSelectedItem();
        String cubierta = (String) combovubierta.getSelectedItem();
        String forma = (String) comboforma.getSelectedItem();
        String decoracion = (String) combodecora.getSelectedItem();
        String tamano = (String) combotama.getSelectedItem();

        // 2. Crea el objeto del modelo con todos los datos, incluyendo el relleno
        PedidoPersonalizado2Model pedido = new PedidoPersonalizado2Model(cliente, ocasion, tipoPan, sabor, cubierta, forma, decoracion, tamano);

        // 3. Pasa el objeto del modelo a la siguiente pantalla
        FrmPastelPersonalizado2 frmPastel2 = new FrmPastelPersonalizado2(pedido);

        // 4. Muestra la nueva ventana y cierra la actual
        frmPastel2.setVisible(true);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatras1;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JComboBox<String> combocliente;
    private javax.swing.JComboBox<String> combodecora;
    private javax.swing.JComboBox<String> comboforma;
    private javax.swing.JComboBox<String> comboocasion;
    private javax.swing.JComboBox<String> combosabor;
    private javax.swing.JComboBox<String> combotama;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JComboBox<String> combovubierta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
