/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.utxicotepec.saborlocal.Vendedor;

import java.text.ParseException;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import mx.edu.utxicotepec.saborlocal.Controllers.ClientesController;
import mx.edu.utxicotepec.saborlocal.Controllers.PedidoController;
import mx.edu.utxicotepec.saborlocal.Controllers.Pasteles;
import mx.edu.utxicotepec.saborlocal.Controllers.Tamanio;
import mx.edu.utxicotepec.saborlocal.Vendedor.FrmPedidoConfirmado;
import mx.edu.utxicotepec.saborlocal.DAOS.ClientesModel;
import mx.edu.utxicotepec.saborlocal.DAOS.PedidoModel;

/**
 *
 * @author xidon
 */
public class FrmRegistroPedido extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRegistroPedido.class.getName());

    /**
     * Creates new form FrmRegistroPedido
     */
    public FrmRegistroPedido() {
        initComponents();
        cargarPasteles();
        cargarTamanios();
        cargarClientes();
        comboseleccion.addActionListener(e -> actualizarCosto());
        combotamanio.addActionListener(e -> actualizarCosto());
        actualizarCosto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnatras = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboseleccion = new javax.swing.JComboBox<>();
        combocliente = new javax.swing.JComboBox<>();
        combotamanio = new javax.swing.JComboBox<>();
        txtmensaje = new javax.swing.JTextField();
        txtanio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtdia = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnpastelper = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 240, 217));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));

        jPanel2.setBackground(new java.awt.Color(185, 157, 179));
        jPanel2.setForeground(new java.awt.Color(185, 157, 179));
        jPanel2.setPreferredSize(new java.awt.Dimension(1440, 100));

        btnatras.setBackground(new java.awt.Color(185, 157, 179));
        btnatras.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnatras.setForeground(new java.awt.Color(255, 240, 217));
        btnatras.setIcon(new javax.swing.ImageIcon("C:\\Users\\xidon\\Documents\\NetBeansProjects\\SaborLocal\\resources\\imgs\\Arrow 2.png")); // NOI18N
        btnatras.setPreferredSize(new java.awt.Dimension(100, 100));
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\xidon\\Documents\\NetBeansProjects\\SaborLocal\\resources\\imgs\\volver.png")); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registro Pedido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addContainerGap(539, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(255, 240, 217));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccion del pastel");

        jLabel3.setBackground(new java.awt.Color(255, 240, 217));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Seleccione tamaño");

        jLabel4.setBackground(new java.awt.Color(255, 240, 217));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cliente");

        jLabel6.setBackground(new java.awt.Color(255, 240, 217));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Mensaje");

        jLabel7.setBackground(new java.awt.Color(255, 240, 217));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Costo");

        comboseleccion.setBackground(new java.awt.Color(255, 255, 255));
        comboseleccion.setForeground(new java.awt.Color(0, 0, 0));
        comboseleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combocliente.setBackground(new java.awt.Color(255, 255, 255));
        combocliente.setForeground(new java.awt.Color(0, 0, 0));
        combocliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combotamanio.setBackground(new java.awt.Color(255, 255, 255));
        combotamanio.setForeground(new java.awt.Color(0, 0, 0));
        combotamanio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtmensaje.setBackground(new java.awt.Color(255, 255, 255));
        txtmensaje.setForeground(new java.awt.Color(0, 0, 0));
        txtmensaje.setToolTipText("");

        txtanio.setBackground(new java.awt.Color(255, 255, 255));
        txtanio.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtanio.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setBackground(new java.awt.Color(255, 240, 217));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("yyyy");

        txtmes.setBackground(new java.awt.Color(255, 255, 255));
        txtmes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtmes.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setBackground(new java.awt.Color(255, 240, 217));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("mm");

        jLabel10.setBackground(new java.awt.Color(255, 240, 217));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("dd");

        txtdia.setBackground(new java.awt.Color(255, 255, 255));
        txtdia.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtdia.setForeground(new java.awt.Color(0, 0, 0));

        btnguardar.setBackground(new java.awt.Color(255, 240, 217));
        btnguardar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(0, 0, 0));
        btnguardar.setText("Siguiente");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnpastelper.setBackground(new java.awt.Color(203, 125, 47));
        btnpastelper.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnpastelper.setForeground(new java.awt.Color(0, 0, 0));
        btnpastelper.setText("Crear Pastel Personalizado");
        btnpastelper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpastelperActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 240, 217));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Fecha de entrega");

        lblCosto.setBackground(new java.awt.Color(255, 255, 255));
        lblCosto.setForeground(new java.awt.Color(0, 0, 0));
        lblCosto.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboseleccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnpastelper, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(10, 10, 10)))
                    .addComponent(lblCosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(180, 180, 180))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(combotamanio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(169, 169, 169)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combocliente, 0, 396, Short.MAX_VALUE)
                                    .addComponent(txtmensaje))
                                .addGap(30, 30, 30))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(168, 168, 168))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(575, 575, 575)
                    .addComponent(jLabel11)
                    .addContainerGap(601, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combotamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpastelper, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(494, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(488, 488, 488)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        // TODO add your handling code here:
        //Boton de funcion para ir nuevamente a la pantalla del vendedor
        FrmMenuVendedor frmvendedor = new FrmMenuVendedor();
        frmvendedor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnatrasActionPerformed

    private void btnpastelperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpastelperActionPerformed
        // TODO add your handling code here:
        FrmPastelPersonalizado frmpedos = new FrmPastelPersonalizado();
        frmpedos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpastelperActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        guardarPedido();
    }//GEN-LAST:event_btnguardarActionPerformed

    public void guardarPedido() {
        try {
            // 1. Obtener los datos del formulario
            String tamanioSeleccionado = (String) combotamanio.getSelectedItem();
            String pastelSeleccionado = (String) comboseleccion.getSelectedItem();
            String clienteSeleccionado = (String) combocliente.getSelectedItem();
            String mensaje = txtmensaje.getText().trim();
            String anio = txtanio.getText().trim();
            String mes = txtmes.getText().trim();
            String dia = txtdia.getText().trim();

            // 2. Validar que los campos obligatorios no estén vacíos
            if (tamanioSeleccionado == null || pastelSeleccionado == null || clienteSeleccionado == null || mensaje.isEmpty() || anio.isEmpty() || mes.isEmpty() || dia.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 3. Validar y construir la fecha de entrega
            String fechaEntrega;
            try {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
                sdf.setLenient(false);
                fechaEntrega = anio + "-" + mes + "-" + dia;
                sdf.parse(fechaEntrega);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "La fecha de entrega no es válida. Por favor, verifique el día, mes y año.", "Error de Fecha", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 4. Obtener el ID del cliente de la base de datos
            int idCliente = ClientesController.obtenerIdClientePorNombreCompleto(clienteSeleccionado);
            if (idCliente == -1) {
                JOptionPane.showMessageDialog(this, "Error: No se pudo encontrar el cliente seleccionado.", "Error de cliente", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 5. Asignar el resto de los valores del pedido
            String fechaPedido = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
            String estado = "Pendiente";

            double precioBase = PedidoController.obtenerPrecioPastelDesdeBD(pastelSeleccionado);
            double precioAdicional = PedidoController.obtenerPrecioAdicionalTamanioDesdeBD(tamanioSeleccionado);
            double totalPedido = precioBase + precioAdicional;

            // 6. Crear el objeto del modelo
            PedidoModel nuevoPedido = new PedidoModel(
                    idCliente,
                    fechaPedido,
                    estado,
                    totalPedido,
                    mensaje,
                    fechaEntrega,
                    pastelSeleccionado,
                    tamanioSeleccionado
            );

            // 7. Llamar al controlador para guardar el pedido
            if (PedidoController.guardarPedido(nuevoPedido)) {
                JOptionPane.showMessageDialog(this, "Pedido guardado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                // Abrir la ventana de confirmación y cerrar la actual
                FrmPedidoConfirmado frmpedvi = new FrmPedidoConfirmado(nuevoPedido);
                frmpedvi.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar el pedido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al guardar el pedido.", "Error General", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // ... (código para el Look and Feel) ...

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRegistroPedido().setVisible(true));
    }

    private void cargarPasteles() {
        comboseleccion.removeAllItems();
        List<String> nombresPasteles = Pasteles.mostrarPasteles();
        for (String nombre : nombresPasteles) {
            comboseleccion.addItem(nombre);
        }
    }

    private void cargarTamanios() {
        combotamanio.removeAllItems();
        List<String> nombresTamanios = Tamanio.mostrarTamanios();

        // ➡️ Usar un comparador para ordenar por un orden específico
        Collections.sort(nombresTamanios, new Comparator<String>() {
            @Override
            public int compare(String t1, String t2) {
                if (t1.equals("Chico")) {
                    return -1;
                }
                if (t2.equals("Chico")) {
                    return 1;
                }
                if (t1.equals("Mediano")) {
                    return -1;
                }
                if (t2.equals("Mediano")) {
                    return 1;
                }
                return 0;
            }
        });

        for (String nombre : nombresTamanios) {
            combotamanio.addItem(nombre);
        }
    }

    private void cargarClientes() {
        combocliente.removeAllItems();
        List<ClientesModel> listaClientes = ClientesController.mostrarTodos();
        for (ClientesModel cliente : listaClientes) {
            String nombreCompleto = cliente.getNombre() + " " + cliente.getApellidoPaterno() + " " + cliente.getApellidoMaterno();
            combocliente.addItem(nombreCompleto);
        }
    }

    private void actualizarCosto() {
        String pastelSeleccionado = (String) comboseleccion.getSelectedItem();
        String tamanioSeleccionado = (String) combotamanio.getSelectedItem();

        if (pastelSeleccionado != null && tamanioSeleccionado != null) {
            // Obtener los precios de la base de datos
            double precioBase = PedidoController.obtenerPrecioPastelDesdeBD(pastelSeleccionado);
            double precioAdicional = PedidoController.obtenerPrecioAdicionalTamanioDesdeBD(tamanioSeleccionado);

            // Calcular el costo total
            double costoTotal = precioBase + precioAdicional;

            // Limpiar y agregar el costo al JComboBox
            lblCosto.setText(String.valueOf(costoTotal));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnpastelper;
    private javax.swing.JComboBox<String> combocliente;
    private javax.swing.JComboBox<String> comboseleccion;
    private javax.swing.JComboBox<String> combotamanio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JTextField txtanio;
    private javax.swing.JTextField txtdia;
    private javax.swing.JTextField txtmensaje;
    private javax.swing.JTextField txtmes;
    // End of variables declaration//GEN-END:variables
}
